### ISSUE TITLE
[Bug] Keyboard shortcuts are not working after updated to 10.8

### ISSUE THREAD

**Issue by ArunKathir98** [ApryseSDK/webviewer-ui#1054]
I have update the PDF web viewer version to 10.8.0. Previously I was using 10.1.1 with that keyboard shorcuts are working properly ( Eg: Edit annotation and Press N  -< Opens the comment tool group ). but after updated to latest is not working. Is that i need to enable some kind of configuration and also i did't get error in the console could someone help me on this to resolve this issue.

**WebViewer version** : 10.8.0

**The current behavior** : Key board shortcuts for annotation tools is not working.

**The expected behavior** : Keyboard shortcut should work.

**Comment by bollain** [comment]
Hi @ArunKathir98,

I was not able to reproduce this in our demo which is running 10.8:
https://docs.apryse.com/samples/web/samples/viewing/viewing-with-webcomponent/

Are you able to reproduce it there? If not, it would be helpful if you can provide a sample where the issue happens. The best course of action is to submit this as a support ticket here:
https://apryse.com/form/request
