### ISSUE TITLE
[Feature Request] expose options for instance.UI.print

### ISSUE THREAD

**Issue by piu130** [ApryseSDK/webviewer-ui#1063]
**Is your feature request related to a problem? Please describe.**
We would like to use embedded printing (`instance.UI.useEmbeddedPrint(true)`) but still want to be able to choose which pages it should print. `instance.UI.print` has currently no params.

**Describe the solution you'd like**
The `instance.UI.print` method should expose [the options object seen in helpers/print.js](https://github.com/PDFTron/webviewer-ui/blob/28a787e6ba84cce7c2bcb0de978d2ecd5bf58e4e/src/helpers/print.js#L169-L182). This way we could pass `pagesToPrint` as well as other params like `includeAnnotations`.
 
**Why is this feature important to your users?**
We want a consistent UI and have our own popups and processes. Sometimes the process chooses the pages to print and sometimes we have a custom pop up.

**Desired timeline**
It doesn't look so hard to implement - would be cool to see it soon :)

**Comment by bollain** [comment]
Hi @piu130,

Thanks for this feature request. I'm happy to inform you that we are actively working on improving the printing APIs, with a focus on embedded printing. When this is released I will let you know through this issue.

**Comment by piu130** [comment]
@bollain looks great. Thank you very much.
