### ISSUE TITLE
[Bug] Unable to enter a multi-digit page number in modular UI page controls input

### ISSUE THREAD

**Issue by jszobody** [ApryseSDK/webviewer-ui#1075]
I'm using the Modular UI and ran into an issue that is reproducible with the public Apryse showcase currently. I'll walk through the steps with this public showcase.

We need a PDF file with 10 pages or more to demonstrate this. The default showcase file at https://showcase.apryse.com only has 9 pages, and the toolbar does not show "Open File" by default. Here is how I did it:

1. Go to https://showcase.apryse.com/toolbar-customization/ and you'll find Open File under the hamburger dropdown menu. Use this and select a PDF file on your computer with 10 pages or more.
![CleanShot 2024-08-08 at 14 33 55@2x](https://github.com/user-attachments/assets/5598261b-6c0d-438e-a012-b5051da8db4f)

2. Once loaded, notice that you can click on the current page number in the floating page controls, and type in a multi-digit page number just fine:
![CleanShot 2024-08-08 at 14 33 03@2x](https://github.com/user-attachments/assets/9bfee7ce-86f3-4bce-acbf-1f4fe051c8e1)

3. Now click on Modular UI on the left. This will switch you to the beta UI, with your large PDF still loaded:
![CleanShot 2024-08-08 at 14 34 14@2x](https://github.com/user-attachments/assets/aa926f9c-d835-4561-ad80-46a7d39843b8)

4. Now with the Modular UI, I am completely unable to type in a multi-digit page number into the page controls field. It only accepts a single digit, there is no way to type in 10, 200, etc.
![CleanShot 2024-08-08 at 14 35 05@2x](https://github.com/user-attachments/assets/51a3a03e-172d-4d00-8677-5a9612c6f56d)

This issue is present in my own viewer implementation. I am using `@pdftron/webviewer` 10.11.1 from NPM.

**Comment by bollain** [comment]
Hi @jszobody,

Thanks for testing out the new modular UI and for submitting this report. We have it in our backlog and it should be fixed in the next sprint, if not earlier. It will be part of our 10.12 release - I will update you when it is out.

**Comment by bollain** [comment]
Hi @jszobody - this issue has been fixed:
 Go to:
 https://showcase.apryse.com/
 
 Load the document from the preset files with many pages - then try to input a multi digit page. It should work as expected. 

Let me know if you have any further questions.
