### ISSUE TITLE
[Bug] documentLoaded event fires once after downloadPdf but not second time.

### ISSUE THREAD

**Issue by Mioleris** [ApryseSDK/webviewer-ui#1077]
I have simple implementation.

```
      WebViewer(
        {
          path: '/webviewer',
          initialDoc: null,
          preloadWorker: 'pdf,office',
          fullAPI: true,
          licenseKey: LICENCE_KEY
        },
        document.getElementById(this.webViewerId)
      ).then((instance: WebViewerInstance) => {
        instance.Core.PDFNet.runWithCleanup(
            () => this.callback(instance),
            process.env.LICENCE_KEY
        )
      })
```

Here I prepare webviewer instance. Inside callback I have events like documentLoaded

In my application I have button download. Which calls loadDocument(fileUrl) and it triggers pdfTron event documentLoaded.

So when I click download one time everything works it triggers documentLoaded and inside I have await instance.UI.downloadPdf() and document downloads.

If I try to download another document nothing happens. Event documentLoaded is not triggered at all.

Second time I just noticed that documentUnloaded event was fired.

Version 10.12.0

**Comment by Mioleris** [comment]
Version 10.12.0

**Comment by bollain** [comment]
Hey @Mioleris,

Apologies for the delayed response. This appears to be an issue with the Core side of Webviewer, not the UI. 

Can you submit a support ticket through this portal? 
https://support.apryse.com/support/tickets/new
